# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false


spring:
  aop:
    proxy-target-class: true
    auto: true
#   rabbitmq:
#     host: paascloud-mq-rabbit
#     port: 5672
#     username: guest
#     password: guest
  redis:
     host: 127.0.0.1
     password:
     port: 6379
     timeout: 5000
#   zipkin:
#     rabbitmq:
#       queue: zipkin

# feign 配置
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true

# hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true

#请求处理的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #   typeAliasesPackage: com.example.sys.api.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
  #     sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
tiger:
  swagger2:
    enable: true
    base-package: com.example
    title: Tiger-Cloud
    description: Tiger cloud Restful API docs
    termsOfServiceUrl: http://localhost:8888
    version: 1.0
    apiName: admin
    apiKeyName: admin
# 异步线程池
async:
  corePoolSize: 16     #核心线程数
  maxPoolSize: 64      #最大线程数
  queueCapacity: 200    #队列大小(excel模板最大上传题目数量)
  namePrefix: tiger_async   #线程的名称前缀
  keepAlive: 60 #允许的空闲时间

# url 白名单
#ignore:
#  urls:
#  - /api/user/info/*

# paascloud:
#   auth:
#     jwt:
#       expiredRemainMinutes: 20
#       expiredMinutes: 120
#   aliyun:
#     key:
#       accessKeyId: 'your aliyun accessKeyId'
#       accessKeySecret: 'your aliyun accessKeySecret'
#   qiniu:
#     key:
#       accessKey: 'your qiniu accessKey'
#       secretKey: 'your qiniu secretKey'
#     oss:
#       privateHost: 'your qiniu oss private host'
#       publicHost: 'your qiniu oss public host'
#   alipay:
#     callback:
#       url: http://dev-api.paascloud.net/omc/pay/alipayCallback
#     qrCode:
#       pcPath: /data/file/qrCode/alipay
#       qiniuPath: alipay/QRCode/
#   zk:
#     zkAddressList: paascloud-provider-zk:2181
