spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      # 认证中心
      - id: tiger-auth
        uri: lb://pig-auth
        predicates:
        - Path=/auth/**
#         filters:
#           # 验证码处理
#         - ValidateCodeGatewayFilter
#           # 前端密码解密
#         - PasswordDecoderFilter
      # 模块
      - id: tiger-admin
        uri: lb://tiger-admin
        predicates:
        - Path=/admin/**
#         filters:
#           # 限流配置
#         - name: RequestRateLimiter
#           args:
#             key-resolver: '#{@remoteAddrKeyResolver}'
#             redis-rate-limiter.replenishRate: 10
#             redis-rate-limiter.burstCapacity: 20
#           # 降级配置
#         - name: Hystrix
#           args:
#             name: default
#             fallbackUri: 'forward:/fallback'
#       # 代码生成模块
#       - id: tiger-codegen
#         uri: lb://tiger-codegen
#         predicates:
#         - Path=/gen/**
# swagger butler配置
swagger.butler:
  api-docs-path: v2/api-docs
  swagger-version: 1.0
  auto-generate-from-zuul-routes: true
# 指定要生成的范围
  generate-routes: tiger-auth,tiger-admin
# 忽略某些路由生成
#  ignore-routes:
