# dev
server:
  port: 8082

spring:
   profiles: dev
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/sy_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      druid:
         driver-class-name: com.mysql.jdbc.Driver
   redis:
      password:    # 密码（默认为空）
      timeout: 6000ms  # 连接超时时长（毫秒）
      cluster:
         max-redirects: 3  # 获取失败 最大重定向次数
         nodes:
            192.168.0.148:7000,192.168.0.148:7001,192.168.0.148:7002,192.168.0.148:7003,192.168.0.148:7004,192.168.0.148:7005
      lettuce:
         pool:
            max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
            max-idle: 10 #连接池中的最大空闲连接
            min-idle: 5 #连接池中的最小空闲连接
            max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
   mvc:
      throw-exception-if-no-handler-found: true
   security:
      oauth2:
         jwt:
            signingKey: 123456 # 对称加密秘钥 
   jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss

mybatis:
   mapper-locations: classpath:mapper/*.xml
   configuration:
        map-underscore-to-camel-case: true
        
# Logging配置
logging:
   config:
      classpath: logback.xml
