# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.174.45:3306/sy_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
#    redis:
#       password:    # 密码（默认为空）
#       timeout: 6000ms  # 连接超时时长（毫秒）
#       cluster:
#          max-redirects: 3  # 获取失败 最大重定向次数
#          nodes:
#             39.105.174.45:7000,39.105.174.45:7001,39.105.174.45:7002,39.105.174.45:7003,39.105.174.45:7004,39.105.174.45:7005
#       lettuce:
#          pool:
#             max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
#             max-idle: 10 #连接池中的最大空闲连接
#             min-idle: 5 #连接池中的最小空闲连接
#             max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
#    mvc:
#       throw-exception-if-no-handler-found: true
#    security:
#       oauth2:
#          jwt:
#             signingKey: 123456 # 对称加密秘钥 
#    jackson:
#       time-zone: GMT+8
#       date-format: yyyy-MM-dd HH:mm:ss

# mybatis:
#    mapper-locations: classpath:mapper/*.xml
#    configuration:
#         map-underscore-to-camel-case: true
        
# Logging配置
# logging:
#    config:
#       classpath: logback.xml
